[CRT-84] Make scratch show view read-only
crt25/collimator pull request #152
Opened 2024-12-22 12:02 UTC by Tyratox

2024-12-22 12:02 UTC, Tyratox commented
TODO: Add tests

2024-12-26 19:29 UTC, pierluca requested changes
Minor issue, LGTM otherwise 👍

2024-12-26 19:29 UTC, pierluca commented on apps/scratch/src/pages/__tests__/ShowOnlyCode.spec.tsx
> +  test.only("cannot move blocks", async ({ page: pwPage }) => {
Probably not a `test.only` :-)

2024-12-30 20:55 UTC, pierluca approved these changes

2025-01-01 20:16 UTC, merged