[CRT-5] Session API
crt25/collimator pull request #77
Opened 2024-11-10 22:35 UTC by pierluca

2024-11-10 22:44 UTC, pierluca commented
The CI fails on the front-end, but it's only touching the backend.

2024-11-10 22:46 UTC, pierluca commented on backend/prisma/schema.prisma
> +// Tables to keep intermediate student activity:
This is put in place to collect data for WP3.
I'd appreciate some early feedback.

2024-11-10 22:46 UTC, pierluca commented on backend/src/api/sessions/sessions.service.ts
For now this service is extremely light on the error-checking, it's basically putting all conditions in the `WHERE` part. Its behaviour will be correct, but an element that is not in the expected state will simply not be found.

I plan to improve this in subsequent iterations along with better test coverage.

2024-11-12 07:51 UTC, Tyratox requested changes
Some comments but nothing inherently blocking. The overly aggresive delete is the only thing I would prefer fixing now :)

2024-11-12 07:51 UTC, Tyratox commented on backend/src/api/sessions/sessions.service.ts
> +    const [_find, _del, update] = await this.prisma.$transaction([
TODO for later: transaction handling on a per-request basis

2024-11-12 07:51 UTC, Tyratox commented on backend/src/api/sessions/sessions.service.ts
> +      }),
Can we make this a bit less destructive and only delete the ones not provided back? This way we lose progress on a session task if the session has already started.

2024-11-12 07:51 UTC, Tyratox commented on backend/src/api/sessions/sessions.service.ts
> +    }
factor out in a function?

2024-11-12 07:51 UTC, Tyratox commented on backend/src/api/sessions/dto/existing-session-extended.dto.ts
I think it would be nice to use better names than "extended"

2024-11-29 14:29 UTC, merged